### ISSUE TITLE
Angular 11 support?

### ISSUE THREAD

**Issue by jeffproe** [gabrielbusarello/material2-carousel#13]
Any plans to support Angular 11 (and beyond)?  I'm in the process of upgrading to Angular 11 and I get the following when trying to upgrade Angular Material:
`Package "@ngbmodule/material-carousel" has an incompatible peer dependency to "@angular/material" (requires "^10.0.1", would install "11.2.10")`

Thanks for keeping this project alive!

**Comment by gabrielbusarello** [comment]
Hi, I've been working a lot, this later year, so I could not gave to this project the most support that a wanted.

I'll update to version 13 of Angular, as soon as possible, and will be soon. Sorry about that.
