### ISSUE TITLE
Angular 12 Support

### ISSUE THREAD

**Issue by mahkassem** [gabrielbusarello/material2-carousel#16]
Any plans for Angular 12 support?

npm ERR! Could not resolve dependency:
npm ERR! peer @angular/material@"^10.0.1" from @ngbmodule/material-carousel@0.7.1

**Comment by ez5504** [comment]
Attempting to resolve this with PR #22

**Comment by gabrielbusarello** [comment]
Hi, I've been working a lot, this later year, so I could not gave to this project the most support that a wanted.

I'll update to version 13 of Angular, as soon as possible, and will be soon. Sorry about that.
