### ISSUE TITLE
Facing issue "cannot find name 'MouseWheelEvent'." in Angular 13

### ISSUE THREAD

**Issue by tohedul** [gabrielbusarello/material2-carousel#28]
Hi, I'm facing "cannot find name 'MouseWheelEvent'." issue when using this in my Angular 13 project. Also facing in Angular 12 too. Can anyone please help me out?

**Comment by MunkoS** [comment]
+

**Comment by YukeshM** [comment]
add the following code **interface MouseWheelEvent extends WheelEvent {}** at the end of the file 
carousel.component.d.ts

**Comment by gabrielbusarello** [comment]
Merged
