### ISSUE TITLE
Error while building the component

### ISSUE THREAD

**Issue by subham-spacer** [gabrielbusarello/material2-carousel#48]
ERROR in node_modules/@ngbmodule/material-carousel/lib/carousel.module.d.ts:2:10 - error TS2305: Module '"@angular/compiler/src/core"' has no exported member 'ModuleWithProviders'.

2 import { ModuleWithProviders } from '@angular/compiler/src/core';
           ~~~~~~~~~~~~~~~~~~~


I am using Angular version 14+. Please help me resolve the issue.

**Comment by wadie** [comment]
Try using this package instead
https://www.npmjs.com/package/material2-carousel

**Comment by subham-spacer** [comment]
thanks @wadie
